### ISSUE TITLE
Stucks with "Waiting for programs to be added..." message

### ISSUE THREAD

**Issue by cihadturhan** [spite/ShaderEditorExtension#18]
When I click button to reload and activate shader editor on a webGL page, I'm seeing this title and it doesn't load the shader screen.

**Comment by spite** [comment]
Knowing what page are you trying to run the editor on would help.

**Comment by cihadturhan** [comment]
Hello @spite, 
Sorry I thought you already know that error. Try it on [this example](http://toji.github.io/webgl2-particles/)

Chrome Version: 45.0.2454.15 beta-m (64-bit)
Plugin Version: 1.0.15 (beta)

Let me know if you need more info

**Comment by spite** [comment]
That's a WebGL2 example of Transform Feedback. The Shader Editor is for WebGL for now.

**Comment by brianchirls** [comment]
I have the same problem on every web page I try, even on non-WebGL2 examples, such as this one: http://threejs.org/examples/webgl_buffergeometry_custom_attributes_particles.html

Though there is no "Waiting..." message - just the welcome screen with the reload button.

Chrome Version 45.0.2454.85 (64-bit)
Plugin Version: 1.0.15 (beta)

**Comment by spite** [comment]
Is it still happening? I was having the same issue yesterday, but it seems to be working again now.

**Comment by brianchirls** [comment]
I'm seeing a SecurityError at panel.js:1035. I'm not in incognito mode, but I do have third-party cookies blocked. Seems to be the same as this:
https://github.com/disconnectme/port/issues/1

Certainly, `try...catch` block would fix it, though I'm not sure how it'd affect the functionality of the extension. Have you considered using `chrome.storage`?
https://developer.chrome.com/extensions/storage

Thanks

**Comment by spite** [comment]
It's probably that. I'll check what can be done.

**Comment by spite** [comment]
I've changed the way settings are stored and accessed. In v1.0.16.1 should be fixed. Can you try and confirm? Thanks!

**Comment by brianchirls** [comment]
Yup, it works now! Thank you!

**Comment by cihadturhan** [comment]
The issue is closed but the problem still persists at least for my pc.

Please check it on [an experiment I made](http://cihadturhan.com/lab/overwerk-2m/)

If it works for you, then it's related to my pc.

Thanks

**Comment by spite** [comment]
That seems to be a different issue. The closed one was due to the Block Third Party Cookes + localStorage on the extension. I'll debug that experiment as soon as I can.
